# -*- coding: utf-8 -*-
"""data download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJZO7lxT5Wa6ut9PTysNkJY2Uz3wEsNF
"""

import requests, pandas as pd, numpy as np, datetime

## Fetch historical data for [ETH, SOL, AVAX, BNB, ADA] using CoinGecko's public API

## Constants
base_URL = "https://api.coingecko.com/api/v3"
endpoint = "/coins/{id}/market_chart"
vs_currency = "usd"
days = 365
interval = "daily"
coins = ["ethereum", "solana", "avalanche-2", "binancecoin", "cardano"]


def fetch_coin_history(token_id, vs_currency="usd", days=365, interval="daily"):
    url = base_URL + endpoint.format(id=token_id)

    params = {
        "vs_currency": vs_currency,
        "days": days,
        "interval": interval
    }

    r = requests.get(url, params=params)
    data = r.json()
    prices = data["prices"]
    df = pd.DataFrame(prices, columns=["timestamp", f"{token_id.upper()}price"])
    df["date"] = pd.to_datetime(df["timestamp"], unit="ms").dt.date

    df = df[["date", f"{token_id.upper()}price"]]
    return df


## generate dataframes and merge them all
dfs = [fetch_coin_history(coin) for coin in coins]

from functools import reduce
df_all = reduce(lambda left, right: pd.merge(left, right, on="date"), dfs)

print(df_all.head(10))

df_all.to_csv("data.csv", index=False)
